import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'accounts',
      columns: [
        { name: 'bank_name', type: 'string' },
        { name: 'account_name', type: 'string' },
        { name: 'account_number', type: 'string' },
        { name: 'branch', type: 'string', isOptional: true },
        { name: 'account_type', type: 'string' },
        { name: 'opening_balance', type: 'number' },
        { name: 'current_balance', type: 'number' },
        { name: 'currency', type: 'string' },
        { name: 'is_active', type: 'boolean' },
        { name: 'icon_name', type: 'string', isOptional: true },
        { name: 'color', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'transactions',
      columns: [
        { name: 'account_id', type: 'string', isIndexed: true },
        { name: 'type', type: 'string' },
        { name: 'amount', type: 'number' },
        { name: 'description', type: 'string' },
        { name: 'category', type: 'string' },
        { name: 'source_type', type: 'string' },
        { name: 'reference_id', type: 'string', isOptional: true },
        { name: 'balance_after', type: 'number' },
        { name: 'transaction_date', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'loans',
      columns: [
        { name: 'title', type: 'string' },
        { name: 'bank_name', type: 'string' },
        { name: 'loan_account_number', type: 'string' },
        { name: 'disbursed_amount', type: 'number' },
        { name: 'outstanding_principal', type: 'number' },
        { name: 'annual_interest_rate', type: 'number' },
        { name: 'tenor_months', type: 'number' },
        { name: 'emi_amount', type: 'number' },
        { name: 'start_date', type: 'number' },
        { name: 'next_due_date', type: 'number' },
        { name: 'linked_account_id', type: 'string', isIndexed: true },
        { name: 'status', type: 'string' },
        { name: 'loan_type', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'loan_payments',
      columns: [
        { name: 'loan_id', type: 'string', isIndexed: true },
        { name: 'payment_number', type: 'number' },
        { name: 'payment_date', type: 'number' },
        { name: 'emi_amount', type: 'number' },
        { name: 'principal_component', type: 'number' },
        { name: 'interest_component', type: 'number' },
        { name: 'outstanding_principal_after', type: 'number' },
        { name: 'status', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'fdrs',
      columns: [
        { name: 'fdr_number', type: 'string' },
        { name: 'bank_name', type: 'string' },
        { name: 'linked_account_id', type: 'string', isIndexed: true },
        { name: 'principal_amount', type: 'number' },
        { name: 'tenor_months', type: 'number' },
        { name: 'annual_interest_rate', type: 'number' },
        { name: 'source_tax_percent', type: 'number' },
        { name: 'payout_frequency', type: 'string' },
        { name: 'start_date', type: 'number' },
        { name: 'maturity_date', type: 'number' },
        { name: 'net_monthly_return', type: 'number' },
        { name: 'projected_maturity_value', type: 'number' },
        { name: 'status', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'fdr_disbursements',
      columns: [
        { name: 'fdr_id', type: 'string', isIndexed: true },
        { name: 'disbursement_date', type: 'number' },
        { name: 'gross_amount', type: 'number' },
        { name: 'tax_deducted', type: 'number' },
        { name: 'net_amount', type: 'number' },
        { name: 'is_credited', type: 'boolean' },
        { name: 'linked_transaction_id', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'sanchaypatra',
      columns: [
        { name: 'certificate_number', type: 'string' },
        { name: 'sanchaypatra_type', type: 'string' },
        { name: 'investment_amount', type: 'number' },
        { name: 'issue_date', type: 'number' },
        { name: 'maturity_date', type: 'number' },
        { name: 'annual_interest_rate', type: 'number' },
        { name: 'source_tax_percent', type: 'number' },
        { name: 'profit_interval', type: 'string' },
        { name: 'linked_account_id', type: 'string', isIndexed: true },
        { name: 'net_profit_per_interval', type: 'number' },
        { name: 'projected_maturity_value', type: 'number' },
        { name: 'status', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'sanchaypatra_coupons',
      columns: [
        { name: 'sanchaypatra_id', type: 'string', isIndexed: true },
        { name: 'coupon_date', type: 'number' },
        { name: 'gross_amount', type: 'number' },
        { name: 'tax_deducted', type: 'number' },
        { name: 'net_amount', type: 'number' },
        { name: 'is_collected', type: 'boolean' },
        { name: 'linked_transaction_id', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'budget_categories',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'icon_name', type: 'string' },
        { name: 'color', type: 'string' },
        { name: 'monthly_limit', type: 'number' },
        { name: 'is_active', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'expenses',
      columns: [
        { name: 'category_id', type: 'string', isIndexed: true },
        { name: 'account_id', type: 'string', isIndexed: true },
        { name: 'amount', type: 'number' },
        { name: 'description', type: 'string' },
        { name: 'expense_date', type: 'number' },
        { name: 'is_recurring', type: 'boolean' },
        { name: 'recurrence_rule', type: 'string', isOptional: true },
        { name: 'linked_transaction_id', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'income_sources',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'source_type', type: 'string' },
        { name: 'amount', type: 'number' },
        { name: 'frequency', type: 'string' },
        { name: 'income_date', type: 'number' },
        { name: 'linked_account_id', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'sync_metadata',
      columns: [
        { name: 'entity_type', type: 'string' },
        { name: 'last_synced_at', type: 'number' },
        { name: 'checksum', type: 'string' },
        { name: 'cloud_provider', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
  ],
});
